[package]
name = "benches"
version = "0.0.0"
publish = false
edition = "2021"

[dependencies]
rar = { path = "../rar" }
criterion = "0.5.1"
rand = "0.8"
rand_chacha = "0.3"

[[bench]]
name = "bench"
path = "bench.rs"
harness = false
